Implement regexp and nin filtering
strongloop/loopback-filters pull request #20
Opened 2017-11-01 08:17 UTC by yshing

### Description
Implement `regexp` and `nin` filtering.

#### Related issues

- connect to https://github.com/strongloop/loopback-filters/issues/14

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

2017-11-01 08:17 UTC, slnode commented
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

2017-11-01 08:17 UTC, slnode commented
Can one of the admins verify this patch?

2017-11-01 17:45 UTC, b-admike reviewed
@yshing thank you for your contribution. I have left some comments, and on top of those, could you add a few more test cases for other conditions in your conditional statements? For example, a test case for when you're passing in a string for `regexp` [here](https://github.com/strongloop/loopback-filters/pull/20/files#diff-168726dbe96b3ce427e7fedce31bb0bcR162). Another example would be when you don't pass in valid values to either the `nin` or `regexp` filters.

2017-11-01 17:45 UTC, b-admike commented on index.js
> +        if (example.nin[i] == value) {
`example.nin[i] === value` here

2017-11-01 17:45 UTC, b-admike commented on test/filter.test.js
> +      console.log('err', err)
Let's handle the error with either `should.exist(err)` or `should.not.exist(err)` here, and subsequent check/s if it doesn't.

2017-11-01 17:45 UTC, b-admike commented on test/filter.test.js
> +          should.exist(err);
one more check here to verify the error message would be great.

2017-11-01 17:48 UTC, b-admike requested changes
See above

2017-11-04 05:34 UTC, yshing commented on index.js
> +        if (example.nin[i] == value) {
Nope, should keep the similar implementation as the current inq.
If need change, both inq and nin should get changed.

2017-12-05 15:11 UTC, b-admike approved these changes
LGTM, just needs a rebase, and we should be able to land.

2017-12-05 15:11 UTC, b-admike commented on index.js
> +        if (example.nin[i] == value) {
I'm okay to keep it as is.

2017-12-05 19:22 UTC, b-admike commented
@yshing Thank you for your contribution. I have landed this patch 🎉.

2017-12-05 19:23 UTC, merged