chore: update LTS stats to End-of-Life
strongloop/loopback-filters pull request #37
Opened 2020-12-31 01:16 UTC by achrinza

see https://github.com/strongloop/loopback-next/issues/6957

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-filters) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

2021-01-12 12:03 UTC, bajtos requested changes

2021-01-12 12:03 UTC, bajtos commented on README.md
> +will be provided or accepted. (See
IBM will keep providing LB3 support for customers using IBM API Connect product. Let's use the following message please:

```suggestion
**⚠️ LoopBack 3 has reached end of life. We are no longer accepting pull requests or providing 
support for community users. The only exception is fixes for critical  bugs and security 
vulnerabilities provided as part of support for IBM API Connect customers. (See
```

2021-01-21 01:09 UTC, dhmlau approved these changes

2021-01-26 15:43 UTC, bajtos approved these changes
👍🏻

2021-01-26 15:43 UTC, merged

2021-01-26 15:43 UTC, bajtos commented
Landed, thank you @achrinza ❤️